import kfp
from kfp import dsl
from kfp.components import func_to_container_op

@dsl.pipeline(name='First Pipeline', description='Applies Decision Tree and Logistic Regression for classification problem.')
def first_pipeline():

    # Loads the yaml manifest for each component
    download = kfp.components.load_component_from_file('./download_data.yaml')
    extremegboost = kfp.components.load_component_from_file('./extremegboost.yaml')
    evidently_monitoring = kfp.components.load_component_from_file('./evidently_monitoring.yaml')

    # Run download_data task
    download_task = download()

    # Run tasks "extremegboost" and "evidently_monitoring" given
    # the output generated by "download_task".
    extremegboost_task = extremegboost(download_task.output)
    evidently_monitoring_task = evidently_monitoring(extremegboost_task.output)

kfp.compiler.Compiler().compile(first_pipeline, 'FirstPipeline2.zip')

client = kfp.Client(<public-link-to-Kubeflow-pipeline>)

EXPERIMENT_NAME = 'my-pipeline1'
experiment = client.create_experiment(name=EXPERIMENT_NAME)

run = client.run_pipeline(experiment.id, 'mypipeline-run1', 'FirstPipeline2.zip')